### ISSUE TITLE
php artisan vendor:publish

### ISSUE THREAD

**Issue by jeffochoa** [laravel-validation-rules/timezone#3]
As you are creating custom validation rules, it would be possible someone want or need to add some extra logic for their project. It would be a nice addition to have the hability of moving this custom class from the vendor directory to the app directory.

**Comment by ssx** [comment]
@jeffochoa,

Will keep this in mind, at present I'm not too sure any of the rules will have a requirement of something as heavy as config. Some packages do have service provides so the individual ones can add it to their package if needed.
