### ISSUE TITLE
[Proposal] use testbench

### ISSUE THREAD

**Issue by clarkeash** [laravel-validation-rules/timezone#5]
Would it be worth switching to use [testbench](https://github.com/orchestral/testbench) for your tests? It allows you to write your tests like you would in a Laravel application.
If you look [here](https://github.com/laravel-validation-rules/ip/blob/master/tests/Feature/IPAddressTest.php#L18) I just use `Validator::make()` without any setup.

**Comment by ssx** [comment]
Always felt that was a little overkill for this, I use some of the rules outside of Laravel as well, so would prefer not to tie it to testbench for the time being. Great suggestion thought and thanks for catching the typo (maybe I was just trying to be down with teh kids 😉)
